name: PR comment
on: [pull_request]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Sample message -> ${{ github.event.changes }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
