name: PR comment
on: [pull_request]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: pierre-ernst/actions-comment-pull-request@master
        with:
          # file-match: '["package\.json"]'
          message: '$file on $owner/$repo has changed'
          # ghToken: ${{ secrets.GITHUB_TOKEN }}
