name: PR comment
on: [pull_request]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ format('-> {0} %%% {1}', github.event.changes, github.repository) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
