name: PR comment
on: [pull_request]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ format('-> {0} / {1} / {2} / {3}', github.event.repository.owner.login, github.event.repository.name, github.event.after, github.event.pull_request.number) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
